seed_everything: 42

trainer:
  gpus: 1
  max_epochs: 15

optimizer:
  class_path: torch.optim.NAdam
  init_args:
    lr: 0.001
    weight_decay: 0.0001

lr_scheduler:
  class_path: torch.optim.lr_scheduler.MultiStepLR
  init_args:
    milestones: [5]
    gamma: 0.1

model:
  use_cnnrnn: False
  d_model: 128
  t_config:
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    num_layers: 2
  embed_size: 256
  lstm_config:
    hidden_size: 256
    num_layers: 1
  max_output_len: 256

data:
  batch_size: 8
  num_workers: 6
  pin_memory: false

ckpt_path: null
